/** Get Dashboard  Top selling data */

export const API_SUCCESS = "API_SUCCESS";
export const API_FAIL = "API_FAIL";
export const GET_TOP_SELLING_PRODUCT = "GET_TOP_SELLING_PRODUCT";
export const GET_EARNING_DATA = "GET_EARNING_DATA";

export const GET_STORE_REPORT = " GET_STORE_REPORT"
export const GET_STORE_REPORT_FAIL = " GET_STORE_REPORT_FAIL"
export const GET_STORE_REPORT_SUCCESS = " GET_STORE_REPORT_SUCCESS"

export const GET_STORE_EARNINGS = " GET_STORE_EARNINGS"
export const GET_STORE_EARNINGS_FAIL = " GET_STORE_EARNINGS_FAIL"
export const GET_STORE_EARNINGS_SUCCESS = " GET_STORE_EARNINGS_SUCCESS"

export const GET_TOP_EARNERS = " GET_TOP_EARNERS"
export const GET_TOP_EARNERS_FAIL = "GET_TOP_EARNERS_FAIL"
export const GET_TOP_EARNERS_SUCCESS = "GET_TOP_EARNERS_SUCCESS"